/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */

  // tutorialSidebar: {
  //   "About Me": ["about-me", "skill-set"],
  //   Project: ["projects", "boc", "ies", "asl"]
  // }

  // mySidebar: [
  //   {
  //     label: "boc",
  //     type: "ref",
  //     id: "project-experience/boc" // Document id (string).
  //   },
  //   {
  //     label: "ies",
  //     type: "ref",
  //     id: "project-experience/ies" // Document id (string).
  //   }
  // ]

  mySidebar: [
    {
      type: "category",
      label: "About Me",
      collapsed: true,
      items: [
        { type: "autogenerated", dirName: "about-me" },
        { type: "autogenerated", dirName: "education-certifications" }
      ]
    },
    {
      type: "category",
      label: "Project Experience",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "project-experience" }]
    },
    // {
    //   type: "category",
    //   label: "Contacts",
    //   collapsed: true,
    //   items: [
    //     {
    //       type: "ref",
    //       label: "Contacts", // The link label
    //       id: "contacts" // The internal path
    //     }
    //   ]
    // },
    "contacts"

    // "intro",
    // {
    //   type: "category",
    //   label: "Tutorials",
    //   items: [
    //     "about-me/about-me",
    //     {
    //       type: "autogenerated",
    //       dirName: "about-me" // Generate sidebar slice from docs/tutorials/easy
    //     },
    //     "about-me/skill-set",
    //     {
    //       type: "autogenerated",
    //       dirName: "project-experience" // Generate sidebar slice from docs/tutorials/hard
    //     },
    //     "intro"
    //   ]
    // },
    // {
    //   type: "autogenerated",
    //   dirName: "about-me" // Generate sidebar slice from docs/guides
    // },
    // {
    //   type: "category",
    //   label: "Community",
    //   items: ["about-me/about-me", "about-me/skill-set"]
    // }
  ]
};
